In [1]:
import torch

In [2]:
x = torch.rand(3)

In [3]:
print(x)

tensor([0.1596, 0.1664, 0.7873])


In [4]:
x = torch.ones(2,2,dtype=torch.float16)

In [5]:
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [6]:
x = torch.tensor([2.5,0.1])

In [7]:
print(x)

tensor([2.5000, 0.1000])


In [8]:
torch.cuda.is_available()

True

In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [10]:
x

tensor([[0.6754, 0.3602],
        [0.2932, 0.3465]])

In [11]:
y

tensor([[0.3977, 0.5286],
        [0.0448, 0.3771]])

In [12]:
z = x + y
z

tensor([[1.0731, 0.8889],
        [0.3381, 0.7237]])

In [13]:
z = torch.add(x,y)

In [14]:
z

tensor([[1.0731, 0.8889],
        [0.3381, 0.7237]])

In [15]:
y.add_(x)

tensor([[1.0731, 0.8889],
        [0.3381, 0.7237]])

In [16]:
z = x-y
z

tensor([[-0.3977, -0.5286],
        [-0.0448, -0.3771]])

In [17]:
z = torch.sub(x,y)
z

tensor([[-0.3977, -0.5286],
        [-0.0448, -0.3771]])

In [18]:
y.sub_(x)

tensor([[0.3977, 0.5286],
        [0.0448, 0.3771]])

In [19]:
z = x*y
z

tensor([[0.2686, 0.1904],
        [0.0131, 0.1307]])

In [20]:
z = torch.mul(x,y)
z

tensor([[0.2686, 0.1904],
        [0.0131, 0.1307]])

In [21]:
z = x/y
z

tensor([[1.6985, 0.6815],
        [6.5424, 0.9188]])

In [22]:
z = torch.div(x,y)
z

tensor([[1.6985, 0.6815],
        [6.5424, 0.9188]])

In [23]:
x = torch.rand(5,3)

In [24]:
x

tensor([[0.3273, 0.9871, 0.2732],
        [0.9891, 0.3668, 0.5858],
        [0.5464, 0.6999, 0.7324],
        [0.8251, 0.3550, 0.9466],
        [0.0912, 0.6061, 0.3594]])

In [25]:
x[:,0]

tensor([0.3273, 0.9891, 0.5464, 0.8251, 0.0912])

In [26]:
import numpy as np

In [27]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [28]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [29]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [30]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [31]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [32]:
a += 1
a

array([2., 2., 2., 2., 2.])

In [33]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    z = z.to("cpu")

In [34]:
x = torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

### AutoGrad

In [35]:
import torch
x = torch.rand(3)
print(x)

tensor([0.2881, 0.2612, 0.6975])


In [36]:
x = torch.rand(3,requires_grad=True)
print(x)

tensor([0.8572, 0.9192, 0.9919], requires_grad=True)


In [37]:
y = x+2
print(y)

tensor([2.8572, 2.9192, 2.9919], grad_fn=<AddBackward0>)


In [38]:
print(x.grad)

None


In [39]:
z = y*y*2
print(z)

tensor([16.3273, 17.0436, 17.9032], grad_fn=<MulBackward0>)


In [40]:
z = z.mean()
print((z))

tensor(17.0914, grad_fn=<MeanBackward0>)


In [41]:
z.backward()

In [42]:
print(x.grad)

tensor([3.8096, 3.8923, 3.9892])


In [43]:
import torch
x = torch.randn(3,requires_grad=True)
x

tensor([ 0.4538, -0.6379,  0.9296], requires_grad=True)

In [44]:
x.requires_grad_(False)

tensor([ 0.4538, -0.6379,  0.9296])

In [45]:
y = x.detach()
y

tensor([ 0.4538, -0.6379,  0.9296])

In [46]:
with torch.no_grad():
    y = x+2
    print(y)

tensor([2.4538, 1.3621, 2.9296])


In [47]:
# example 1

In [48]:
import torch
weights = torch.ones(4,requires_grad=True)
print(weights)

tensor([1., 1., 1., 1.], requires_grad=True)


In [49]:
for epoch in range(1):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    print(weights)

tensor([3., 3., 3., 3.])
tensor([1., 1., 1., 1.], requires_grad=True)


In [50]:
# through optimizer

In [51]:
import torch
weights = torch.ones(4,requires_grad=True)
optimizer = torch.optim.SGD([weights],lr=0.01)
optimizer.step()
optimizer.zero_grad

<bound method Optimizer.zero_grad of SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)>

In [52]:
# Back Propagation

In [53]:
import torch
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0,requires_grad=True)

In [55]:
# forward pass
y_hat = w*x
loss = (y_hat-y)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [56]:
# backward pass
loss.backward()
print(w.grad)

tensor(-2.)


In [57]:
import tensorflow as tf

In [58]:
tf.__version__

'2.12.0'

In [59]:
torch.version.cuda

'11.8'